language: ruby
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
# rvm:
#   - 2.4.2
before_install:
  - gem update --system
install: gem install jekyll
script: jekyll build
